use serde::{Deserialize, Serialize};

/// Chat roles supported by the runtime.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
}

/// A tool call generated by the language model.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ToolCall {
    pub name: String,
    pub arguments: serde_json::Value,
}

/// A tool result message captured in the transcript.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ToolResult {
    pub name: String,
    pub output: serde_json::Value,
}

/// A single message in the conversation transcript.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Message {
    pub role: Role,
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call: Option<ToolCall>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_result: Option<ToolResult>,
}

impl Message {
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: content.into(),
            tool_call: None,
            tool_result: None,
        }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: content.into(),
            tool_call: None,
            tool_result: None,
        }
    }

    pub fn tool(name: impl Into<String>, output: serde_json::Value) -> Self {
        Self {
            role: Role::Tool,
            content: format!("Result from `{}`", name.into()),
            tool_call: None,
            tool_result: Some(ToolResult {
                name: name.into(),
                output,
            }),
        }
    }
}

